// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkktcO1OB1v8ULgcZg2_PXn6NmPIF2uq4',
    appId: '1:18349526022:web:09cbd370d09bfeaeff0787',
    messagingSenderId: '18349526022',
    projectId: 'outliner-f560b',
    authDomain: 'outliner-f560b.firebaseapp.com',
    storageBucket: 'outliner-f560b.appspot.com',
    measurementId: 'G-8HVQ77H5JZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3N9IV9LGy-FEQqAWf45T-TFPfQfQmlmI',
    appId: '1:18349526022:android:83c34cb1db2d5551ff0787',
    messagingSenderId: '18349526022',
    projectId: 'outliner-f560b',
    storageBucket: 'outliner-f560b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXpDfNyaNbwIyGHCgVhkm2-Ll_drQ21vo',
    appId: '1:18349526022:ios:a096d80cad3c4c09ff0787',
    messagingSenderId: '18349526022',
    projectId: 'outliner-f560b',
    storageBucket: 'outliner-f560b.appspot.com',
    iosBundleId: 'net.libnare.outliner.outliner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXpDfNyaNbwIyGHCgVhkm2-Ll_drQ21vo',
    appId: '1:18349526022:ios:a096d80cad3c4c09ff0787',
    messagingSenderId: '18349526022',
    projectId: 'outliner-f560b',
    storageBucket: 'outliner-f560b.appspot.com',
    iosBundleId: 'net.libnare.outliner.outliner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkktcO1OB1v8ULgcZg2_PXn6NmPIF2uq4',
    appId: '1:18349526022:web:48a14c3c0da99cf7ff0787',
    messagingSenderId: '18349526022',
    projectId: 'outliner-f560b',
    authDomain: 'outliner-f560b.firebaseapp.com',
    storageBucket: 'outliner-f560b.appspot.com',
    measurementId: 'G-8YCRYD9MFK',
  );
}
